# Generated by Django 5.2.9 on 2026-01-05 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionclienteusuario',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor responsable de este cliente', limit_choices_to={'tipo_usuario__in': ['supervisor', 'gerente']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Responsable'),
        ),
    ]
