# Generated by Django 5.2.9 on 2026-01-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_supervisor_to_cliente_and_asignado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable de este cliente (analista o supervisor)', limit_choices_to={'tipo_usuario__in': ['analista', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
    ]
