# Generated by Django 5.2.9 on 2026-01-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_simplify_cliente_usuario_asignado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionClienteUsuario',
        ),
    ]
