# Generated by Django 5.2.9 on 2026-01-08 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_asignacion_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único para Factory pattern (ej: talana, buk, sap)', unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(help_text='Nombre del sistema ERP para mostrar', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del ERP y sus características', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si el ERP está disponible para asignar a clientes', verbose_name='Activo')),
                ('requiere_api', models.BooleanField(default=False, help_text='Si el ERP tiene API para integración directa (reportería)', verbose_name='Requiere API')),
                ('formatos_soportados', models.JSONField(default=list, help_text='Lista de extensiones de archivo: ["xlsx", "csv", "txt"]', verbose_name='Formatos Soportados')),
                ('schema_credenciales', models.JSONField(blank=True, default=dict, help_text='JSON Schema para validar campos de credenciales requeridas', verbose_name='Schema de Credenciales')),
                ('configuracion_parseo', models.JSONField(blank=True, default=dict, help_text='Configuración específica: columnas, hojas, delimitadores, mapeos', verbose_name='Configuración de Parseo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'ERP',
                'verbose_name_plural': 'ERPs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionERPCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credenciales', models.JSONField(blank=True, default=dict, help_text='Credenciales específicas: {token, client_id, base_url, api_key, etc.}', verbose_name='Credenciales')),
                ('fecha_activacion', models.DateField(help_text='Desde cuándo está activa esta configuración', verbose_name='Fecha de Activación')),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Fecha límite de vigencia (null = sin vencimiento)', null=True, verbose_name='Fecha de Expiración')),
                ('activo', models.BooleanField(default=True, help_text='Si esta configuración está habilitada', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, help_text='Notas sobre esta configuración (contacto técnico, observaciones)', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_erp', to='core.cliente', verbose_name='Cliente')),
                ('erp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='core.erp', verbose_name='ERP')),
            ],
            options={
                'verbose_name': 'Configuración ERP de Cliente',
                'verbose_name_plural': 'Configuraciones ERP de Clientes',
                'ordering': ['cliente', 'erp'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'erp'), name='unique_cliente_erp')],
            },
        ),
    ]
