# Generated by Django 5.2.9 on 2026-01-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_cleanup_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.EmailField(blank=True, help_text='Email del usuario al momento de la acción (inmutable)', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del navegador/cliente')),
                ('accion', models.CharField(db_index=True, help_text='Tipo de acción: create, update, delete, login, logout, export', max_length=20)),
                ('modelo', models.CharField(db_index=True, help_text='Modelo afectado (ej: validador.Cierre)', max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='ID del objeto afectado', null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación string del objeto', max_length=255)),
                ('cliente_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='ID del cliente asociado (para filtros de acceso)', null=True)),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior del objeto (para UPDATE/DELETE)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Nuevo estado del objeto (para CREATE/UPDATE)', null=True)),
                ('endpoint', models.CharField(blank=True, help_text='Endpoint de la API que procesó la acción', max_length=255)),
                ('metodo_http', models.CharField(blank=True, help_text='Método HTTP usado (POST, PUT, PATCH, DELETE)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento de la acción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='core_auditl_usuario_bcfea8_idx'), models.Index(fields=['modelo', 'objeto_id'], name='core_auditl_modelo_2c1abf_idx'), models.Index(fields=['cliente_id', 'timestamp'], name='core_auditl_cliente_fed4d6_idx'), models.Index(fields=['accion', 'timestamp'], name='core_auditl_accion_39de76_idx')],
            },
        ),
    ]
