# Generated by Django 5.2.9 on 2026-01-05 04:21

import apps.validador.models.archivo
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConcepto',
            fields=[
                ('codigo', models.CharField(choices=[('haberes_imponibles', 'Haberes Imponibles'), ('haberes_no_imponibles', 'Haberes No Imponibles'), ('descuentos_legales', 'Descuentos Legales'), ('otros_descuentos', 'Otros Descuentos'), ('aportes_patronales', 'Aportes Patronales'), ('informativos', 'Informativos')], max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('se_compara', models.BooleanField(default=True, help_text='¿Los items de esta categoría se comparan con Novedades?')),
                ('se_incluye_en_incidencias', models.BooleanField(default=True, help_text='¿Los items de esta categoría se incluyen en detección de incidencias?')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Concepto',
                'verbose_name_plural': 'Categorías de Conceptos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2025-01)', max_length=7)),
                ('estado', models.CharField(choices=[('carga_archivos', 'Carga de Archivos'), ('clasificacion_conceptos', 'Clasificación de Conceptos'), ('mapeo_items', 'Mapeo de Items'), ('comparacion', 'Comparación en Proceso'), ('con_discrepancias', 'Con Discrepancias'), ('consolidado', 'Consolidado'), ('deteccion_incidencias', 'Detectando Incidencias'), ('revision_incidencias', 'Revisión de Incidencias'), ('finalizado', 'Finalizado'), ('error', 'Error en Proceso')], default='carga_archivos', max_length=30)),
                ('total_discrepancias', models.PositiveIntegerField(default=0)),
                ('discrepancias_resueltas', models.PositiveIntegerField(default=0)),
                ('total_incidencias', models.PositiveIntegerField(default=0)),
                ('incidencias_aprobadas', models.PositiveIntegerField(default=0)),
                ('es_primer_cierre', models.BooleanField(default=False, help_text='True si es el primer cierre del cliente (sin mes anterior)')),
                ('requiere_clasificacion', models.BooleanField(default=False, help_text='True si hay conceptos nuevos por clasificar')),
                ('requiere_mapeo', models.BooleanField(default=False, help_text='True si hay items nuevos por mapear')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_consolidacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='core.cliente')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_finalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre',
                'verbose_name_plural': 'Cierres',
                'ordering': ['-periodo', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.validador.models.archivo.archivo_upload_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='subido', max_length=20)),
                ('filas_procesadas', models.PositiveIntegerField(default=0)),
                ('errores_procesamiento', models.JSONField(blank=True, default=list)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('libro_remuneraciones', 'Libro de Remuneraciones'), ('movimientos_mes', 'Movimientos del Mes')], max_length=30)),
                ('hojas_encontradas', models.JSONField(blank=True, default=list, help_text='Lista de hojas encontradas en el Excel (para Movimientos)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_version_actual', models.BooleanField(default=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_erp', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Archivo ERP',
                'verbose_name_plural': 'Archivos ERP',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.validador.models.archivo.archivo_upload_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='subido', max_length=20)),
                ('filas_procesadas', models.PositiveIntegerField(default=0)),
                ('errores_procesamiento', models.JSONField(blank=True, default=list)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('novedades', 'Novedades'), ('asistencias', 'Asistencias'), ('finiquitos', 'Finiquitos'), ('ingresos', 'Ingresos')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_version_actual', models.BooleanField(default=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_analista', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Archivo Analista',
                'verbose_name_plural': 'Archivos Analista',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_erp', models.CharField(help_text='Nombre del concepto como aparece en el ERP', max_length=200)),
                ('clasificado', models.BooleanField(default=False)),
                ('fecha_clasificacion', models.DateTimeField(blank=True, null=True)),
                ('ignorar_en_comparacion', models.BooleanField(default=False, help_text='Ignorar este concepto específico en comparaciones')),
                ('multiplicador', models.DecimalField(decimal_places=4, default=1, help_text='Factor multiplicador (si el ERP aplica algún cálculo)', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='validador.categoriaconcepto')),
                ('clasificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_clasificados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Concepto de Cliente',
                'verbose_name_plural': 'Conceptos de Clientes',
                'ordering': ['cliente', 'categoria', 'nombre_erp'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('monto_diferente', 'Monto Diferente'), ('falta_en_erp', 'Falta en ERP'), ('falta_en_cliente', 'Falta en Archivos Cliente'), ('empleado_no_encontrado', 'Empleado No Encontrado'), ('item_no_mapeado', 'Item No Mapeado')], max_length=30)),
                ('origen', models.CharField(choices=[('libro_vs_novedades', 'Libro vs Novedades'), ('movimientos_vs_analista', 'Movimientos vs Archivos Analista')], max_length=30)),
                ('rut_empleado', models.CharField(max_length=12)),
                ('nombre_empleado', models.CharField(blank=True, max_length=200)),
                ('nombre_item', models.CharField(blank=True, help_text='Nombre del item (para casos sin mapeo)', max_length=200)),
                ('monto_erp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monto_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=30)),
                ('detalle_movimiento', models.JSONField(blank=True, default=dict)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias', to='validador.cierre')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias', to='validador.conceptocliente')),
            ],
            options={
                'verbose_name': 'Discrepancia',
                'verbose_name_plural': 'Discrepancias',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('centro_costo', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Empleado de Cierre',
                'verbose_name_plural': 'Empleados de Cierre',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_mes_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_mes_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diferencia_absoluta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variacion_porcentual', models.DecimalField(decimal_places=2, help_text='Variación en porcentaje', max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_resolucion', models.TextField(blank=True, help_text='Justificación de la aprobación/rechazo')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='validador.categoriaconcepto')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='validador.cierre')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='validador.conceptocliente')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-variacion_porcentual'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/')),
                ('nombre_adjunto', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('editado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_incidencias', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='validador.incidencia')),
            ],
            options={
                'verbose_name': 'Comentario de Incidencia',
                'verbose_name_plural': 'Comentarios de Incidencias',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MapeoItemNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_novedades', models.CharField(help_text='Nombre del item como aparece en Novedades', max_length=200)),
                ('fecha_mapeo', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_items', to='core.cliente')),
                ('concepto_erp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_novedades', to='validador.conceptocliente')),
                ('mapeado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeo Item Novedades',
                'verbose_name_plural': 'Mapeos Items Novedades',
                'ordering': ['cliente', 'nombre_novedades'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'Alta/Ingreso'), ('baja', 'Baja/Finiquito'), ('licencia', 'Licencia Médica'), ('vacaciones', 'Vacaciones'), ('permiso', 'Permiso'), ('ausencia', 'Ausencia'), ('otro', 'Otro')], max_length=20)),
                ('origen', models.CharField(choices=[('asistencias', 'Archivo Asistencias'), ('finiquitos', 'Archivo Finiquitos'), ('ingresos', 'Archivo Ingresos')], max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('causal', models.CharField(blank=True, max_length=200)),
                ('datos_raw', models.JSONField(blank=True, default=dict)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_analista', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Movimiento Analista',
                'verbose_name_plural': 'Movimientos Analista',
                'ordering': ['tipo', 'rut'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'Alta/Ingreso'), ('baja', 'Baja/Finiquito'), ('licencia', 'Licencia Médica'), ('vacaciones', 'Vacaciones'), ('permiso', 'Permiso'), ('ausencia', 'Ausencia'), ('otro', 'Otro')], max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('causal', models.CharField(blank=True, max_length=200)),
                ('tipo_licencia', models.CharField(blank=True, max_length=100)),
                ('datos_raw', models.JSONField(blank=True, default=dict)),
                ('hoja_origen', models.CharField(blank=True, max_length=100)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_erp', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Movimiento del Mes (ERP)',
                'verbose_name_plural': 'Movimientos del Mes (ERP)',
                'ordering': ['tipo', 'rut'],
            },
        ),
        migrations.CreateModel(
            name='RegistroConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_original', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='validador.conceptocliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='validador.empleadocierre')),
            ],
            options={
                'verbose_name': 'Registro de Concepto',
                'verbose_name_plural': 'Registros de Conceptos',
            },
        ),
        migrations.CreateModel(
            name='RegistroNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(max_length=12)),
                ('nombre_empleado', models.CharField(blank=True, max_length=200)),
                ('nombre_item', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_novedades', to='validador.cierre')),
                ('mapeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='validador.mapeoitemnovedades')),
            ],
            options={
                'verbose_name': 'Registro de Novedades',
                'verbose_name_plural': 'Registros de Novedades',
            },
        ),
        migrations.CreateModel(
            name='ResumenCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cantidad_conceptos', models.PositiveIntegerField(default=0)),
                ('cantidad_empleados_afectados', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_totales', to='validador.categoriaconcepto')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_categoria', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Resumen por Categoría',
                'verbose_name_plural': 'Resúmenes por Categoría',
            },
        ),
        migrations.CreateModel(
            name='ResumenConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cantidad_empleados', models.PositiveIntegerField(default=0, help_text='Cantidad de empleados con este concepto')),
                ('monto_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='validador.categoriaconcepto')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='validador.cierre')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='validador.conceptocliente')),
            ],
            options={
                'verbose_name': 'Resumen Consolidado',
                'verbose_name_plural': 'Resúmenes Consolidados',
                'ordering': ['categoria', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='ResumenMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'Altas/Ingresos'), ('baja', 'Bajas/Finiquitos'), ('licencia', 'Licencias Médicas'), ('vacaciones', 'Vacaciones'), ('permiso', 'Permisos'), ('ausencia', 'Ausencias')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('total_dias', models.PositiveIntegerField(default=0, help_text='Total de días (para licencias/vacaciones)')),
                ('empleados', models.JSONField(default=list, help_text='Lista de {rut, nombre} afectados')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_movimientos', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Resumen de Movimientos',
                'verbose_name_plural': 'Resúmenes de Movimientos',
            },
        ),
        migrations.AddIndex(
            model_name='cierre',
            index=models.Index(fields=['cliente', '-periodo'], name='validador_c_cliente_a9ca7a_idx'),
        ),
        migrations.AddIndex(
            model_name='cierre',
            index=models.Index(fields=['estado'], name='validador_c_estado_0860ed_idx'),
        ),
        migrations.AddIndex(
            model_name='cierre',
            index=models.Index(fields=['analista', 'estado'], name='validador_c_analist_da8bd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cierre',
            unique_together={('cliente', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='conceptocliente',
            unique_together={('cliente', 'nombre_erp')},
        ),
        migrations.AddIndex(
            model_name='discrepancia',
            index=models.Index(fields=['cierre', 'tipo'], name='validador_d_cierre__b42552_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepancia',
            index=models.Index(fields=['cierre', 'resuelta'], name='validador_d_cierre__3df32c_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepancia',
            index=models.Index(fields=['cierre', 'rut_empleado'], name='validador_d_cierre__dadab0_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadocierre',
            index=models.Index(fields=['cierre', 'rut'], name='validador_e_cierre__5ae924_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empleadocierre',
            unique_together={('cierre', 'rut')},
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['cierre', 'estado'], name='validador_i_cierre__dc73c4_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['cierre', 'categoria'], name='validador_i_cierre__4778da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapeoitemnovedades',
            unique_together={('cliente', 'nombre_novedades')},
        ),
        migrations.AddIndex(
            model_name='movimientoanalista',
            index=models.Index(fields=['cierre', 'tipo'], name='validador_m_cierre__39ddd2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoanalista',
            index=models.Index(fields=['cierre', 'rut'], name='validador_m_cierre__8cb406_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientomes',
            index=models.Index(fields=['cierre', 'tipo'], name='validador_m_cierre__dba10c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientomes',
            index=models.Index(fields=['cierre', 'rut'], name='validador_m_cierre__249ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='registroconcepto',
            index=models.Index(fields=['empleado', 'concepto'], name='validador_r_emplead_5ac5c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroconcepto',
            unique_together={('empleado', 'concepto')},
        ),
        migrations.AddIndex(
            model_name='registronovedades',
            index=models.Index(fields=['cierre', 'rut_empleado'], name='validador_r_cierre__4329f8_idx'),
        ),
        migrations.AddIndex(
            model_name='registronovedades',
            index=models.Index(fields=['cierre', 'nombre_item'], name='validador_r_cierre__b02e3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumencategoria',
            unique_together={('cierre', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='resumenconsolidado',
            unique_together={('cierre', 'concepto')},
        ),
        migrations.AlterUniqueTogether(
            name='resumenmovimientos',
            unique_together={('cierre', 'tipo')},
        ),
    ]
