# Generated by Django 5.2.9 on 2026-01-09 04:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_erp_models'),
        ('validador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoerp',
            name='empleados_procesados',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de empleados procesados del libro'),
        ),
        migrations.AddField(
            model_name='archivoerp',
            name='error_mensaje',
            field=models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló'),
        ),
        migrations.AddField(
            model_name='archivoerp',
            name='headers_clasificados',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de headers ya clasificados'),
        ),
        migrations.AddField(
            model_name='archivoerp',
            name='headers_total',
            field=models.PositiveIntegerField(default=0, help_text='Total de headers encontrados en el libro'),
        ),
        migrations.AddField(
            model_name='archivoerp',
            name='task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea Celery en ejecución', max_length=100),
        ),
        migrations.CreateModel(
            name='ConceptoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_original', models.CharField(help_text='Nombre exacto como aparece en el Excel (ej: "SUELDO BASE", "AFP")', max_length=200)),
                ('header_normalizado', models.SlugField(help_text='Versión normalizada del header para búsqueda/matching', max_length=200)),
                ('categoria', models.CharField(blank=True, choices=[('haberes_imponibles', 'Haberes Imponibles'), ('haberes_no_imponibles', 'Haberes No Imponibles'), ('descuentos_legales', 'Descuentos Legales'), ('otros_descuentos', 'Otros Descuentos'), ('aportes_patronales', 'Aportes Patronales'), ('info_adicional', 'Información Adicional'), ('identificador', 'Identificador (RUT, etc.)'), ('ignorar', 'Ignorar')], help_text='Categoría asignada al concepto', max_length=30, null=True)),
                ('es_identificador', models.BooleanField(default=False, help_text='True si este header contiene RUT/ID del empleado')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que aparece la columna en el Excel')),
                ('activo', models.BooleanField(default=True, help_text='False = soft delete')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece esta clasificación', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_libro', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_libro_creados', to=settings.AUTH_USER_MODEL)),
                ('erp', models.ForeignKey(help_text='ERP del cliente (mismo header puede variar por ERP)', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_libro', to='core.erp')),
            ],
            options={
                'verbose_name': 'Concepto Libro',
                'verbose_name_plural': 'Conceptos Libro',
                'ordering': ['cliente', 'erp', 'orden', 'header_original'],
                'indexes': [models.Index(fields=['cliente', 'erp'], name='validador_c_cliente_e498da_idx'), models.Index(fields=['cliente', 'erp', 'header_normalizado'], name='validador_c_cliente_2ff5ba_idx'), models.Index(fields=['categoria'], name='validador_c_categor_59dfe8_idx')],
                'unique_together': {('cliente', 'erp', 'header_original')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del empleado (formato: 12345678-9)', max_length=12)),
                ('nombre', models.CharField(blank=True, help_text='Nombre completo del empleado (si viene en el libro)', max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('centro_costo', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('datos_json', models.JSONField(default=dict, help_text='\n        Estructura: {\n            "haberes_imponibles": {\n                "SUELDO BASE": 1500000,\n                "BONO PRODUCCION": 200000,\n                "total": 1700000\n            },\n            "haberes_no_imponibles": {...},\n            "descuentos_legales": {...},\n            ...\n        }\n        ')),
                ('total_haberes_imponibles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de todos los haberes imponibles', max_digits=15)),
                ('total_haberes_no_imponibles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de todos los haberes no imponibles', max_digits=15)),
                ('total_descuentos_legales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de descuentos legales (AFP, Salud, etc.)', max_digits=15)),
                ('total_otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de otros descuentos', max_digits=15)),
                ('total_aportes_patronales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de aportes patronales', max_digits=15)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Líquido a pagar (haberes - descuentos)', max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_erp', models.ForeignKey(help_text='Archivo del cual se extrajo este empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_libro', to='validador.archivoerp')),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_libro', to='validador.cierre')),
            ],
            options={
                'verbose_name': 'Empleado Libro',
                'verbose_name_plural': 'Empleados Libro',
                'ordering': ['cierre', 'nombre', 'rut'],
                'indexes': [models.Index(fields=['cierre', 'rut'], name='validador_e_cierre__01e7fb_idx'), models.Index(fields=['archivo_erp'], name='validador_e_archivo_2fa741_idx'), models.Index(fields=['cierre', 'archivo_erp'], name='validador_e_cierre__a07ff7_idx')],
                'unique_together': {('cierre', 'archivo_erp', 'rut')},
            },
        ),
    ]
