# Generated by Django 5.2.9 on 2026-01-12 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_erp_models'),
        ('validador', '0002_archivoerp_empleados_procesados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptolibro',
            options={'ordering': ['cliente', 'erp', 'orden', 'header_original', 'ocurrencia'], 'verbose_name': 'Concepto Libro', 'verbose_name_plural': 'Conceptos Libro'},
        ),
        migrations.AlterUniqueTogether(
            name='conceptolibro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conceptolibro',
            name='es_duplicado',
            field=models.BooleanField(default=False, help_text='True si este header aparece múltiples veces en el Excel'),
        ),
        migrations.AddField(
            model_name='conceptolibro',
            name='header_pandas',
            field=models.CharField(blank=True, help_text='Nombre como pandas lo lee (ej: "BONO.1" para el segundo BONO)', max_length=200),
        ),
        migrations.AddField(
            model_name='conceptolibro',
            name='ocurrencia',
            field=models.PositiveIntegerField(default=1, help_text='Número de ocurrencia si el header está duplicado (1, 2, 3...)'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptolibro',
            unique_together={('cliente', 'erp', 'header_original', 'ocurrencia')},
        ),
        migrations.AddIndex(
            model_name='conceptolibro',
            index=models.Index(fields=['cliente', 'erp', 'header_pandas'], name='validador_c_cliente_d433f4_idx'),
        ),
    ]
