# Generated by Django 5.2.9 on 2026-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0003_alter_conceptolibro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoanalista',
            name='estado',
            field=models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='subido', max_length=30),
        ),
        migrations.AlterField(
            model_name='archivoerp',
            name='estado',
            field=models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='subido', max_length=30),
        ),
    ]
