# Generated by Django 5.2.9 on 2026-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0004_increase_estado_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptolibro',
            name='es_identificador',
        ),
        migrations.AlterField(
            model_name='conceptolibro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('haberes_imponibles', 'Haberes Imponibles'), ('haberes_no_imponibles', 'Haberes No Imponibles'), ('descuentos_legales', 'Descuentos Legales'), ('otros_descuentos', 'Otros Descuentos'), ('aportes_patronales', 'Aportes Patronales'), ('info_adicional', 'Información Adicional'), ('ignorar', 'Ignorar')], help_text='Categoría asignada al concepto', max_length=30, null=True),
        ),
    ]
