# Generated by Django 5.2.10 on 2026-01-13 16:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0005_remove_es_identificador_from_conceptolibro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadolibro',
            name='area',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='datos_json',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='total_aportes_patronales',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='total_descuentos_legales',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='total_haberes_imponibles',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='total_haberes_no_imponibles',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='total_liquido',
        ),
        migrations.RemoveField(
            model_name='empleadolibro',
            name='total_otros_descuentos',
        ),
        migrations.AlterField(
            model_name='empleadolibro',
            name='rut',
            field=models.CharField(help_text='RUT del empleado (formato: 12345678-9)', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del concepto para este empleado', max_digits=15)),
                ('cierre', models.ForeignKey(help_text='Cierre al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='registros_libro', to='validador.cierre')),
                ('concepto', models.ForeignKey(help_text='Concepto clasificado del libro', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='validador.conceptolibro')),
                ('empleado', models.ForeignKey(help_text='Empleado al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='validador.empleadolibro')),
            ],
            options={
                'verbose_name': 'Registro Libro',
                'verbose_name_plural': 'Registros Libro',
                'ordering': ['cierre', 'empleado', 'concepto'],
                'indexes': [models.Index(fields=['cierre', 'empleado'], name='validador_r_cierre__ce2955_idx'), models.Index(fields=['cierre', 'concepto'], name='validador_r_cierre__f97dfd_idx'), models.Index(fields=['empleado', 'concepto'], name='validador_r_emplead_edb663_idx')],
                'unique_together': {('empleado', 'concepto')},
            },
        ),
    ]
