# Generated by Django 5.2.10 on 2026-01-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0007_refactor_mapeoitemnovedades_add_itemnovedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='estado',
            field=models.CharField(choices=[('carga_archivos', 'Carga de Archivos ERP'), ('clasificacion_conceptos', 'Clasificación de Conceptos'), ('carga_novedades', 'Carga de Novedades'), ('mapeo_items', 'Mapeo de Items'), ('comparacion', 'Comparación en Proceso'), ('con_discrepancias', 'Con Discrepancias'), ('consolidado', 'Consolidado'), ('deteccion_incidencias', 'Detectando Incidencias'), ('revision_incidencias', 'Revisión de Incidencias'), ('finalizado', 'Finalizado'), ('error', 'Error en Proceso')], default='carga_archivos', max_length=30),
        ),
    ]
