# Generated by Django 5.2.10 on 2026-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0008_alter_cierre_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnovedades',
            name='nombre_original',
            field=models.CharField(help_text='Nombre exacto como aparece en el Excel', max_length=500),
        ),
        migrations.AlterField(
            model_name='mapeoitemnovedades',
            name='nombre_novedades',
            field=models.CharField(help_text='Nombre del item como aparece en el archivo de Novedades', max_length=500),
        ),
    ]
