# Generated by Django 5.2.10 on 2026-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0009_increase_nombre_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnovedades',
            name='nombre_original',
            field=models.TextField(help_text='Nombre exacto como aparece en el Excel'),
        ),
        migrations.AlterField(
            model_name='mapeoitemnovedades',
            name='nombre_novedades',
            field=models.TextField(help_text='Nombre del item como aparece en el archivo de Novedades'),
        ),
    ]
