# Generated by Django 5.2.10 on 2026-01-15 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_auditlog_model'),
        ('validador', '0010_nombre_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapeoitemnovedades',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mapeoitemnovedades',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='mapeoitemnovedades',
            name='concepto_libro',
        ),
        migrations.RemoveField(
            model_name='mapeoitemnovedades',
            name='erp',
        ),
        migrations.RemoveField(
            model_name='mapeoitemnovedades',
            name='mapeado_por',
        ),
        migrations.RemoveField(
            model_name='registronovedades',
            name='mapeo',
        ),
        migrations.CreateModel(
            name='ConceptoNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_original', models.TextField(help_text='Nombre exacto como aparece en el Excel de novedades')),
                ('header_normalizado', models.SlugField(help_text='Versión normalizada del header para búsqueda/matching', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que aparece la columna en el Excel')),
                ('activo', models.BooleanField(default=True, help_text='False = soft delete')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mapeo', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece este mapeo', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_novedades', to='core.cliente')),
                ('concepto_libro', models.ForeignKey(blank=True, help_text='Concepto del libro al que mapea (null = sin mapear)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_novedades', to='validador.conceptolibro')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_novedades_creados', to=settings.AUTH_USER_MODEL)),
                ('erp', models.ForeignKey(help_text='ERP del cliente', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_novedades', to='core.erp')),
                ('mapeado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_novedades_mapeados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concepto Novedades',
                'verbose_name_plural': 'Conceptos Novedades',
                'ordering': ['cliente', 'erp', 'orden', 'header_original'],
            },
        ),
        migrations.AddField(
            model_name='registronovedades',
            name='concepto_novedades',
            field=models.ForeignKey(blank=True, help_text='Concepto de novedades (conecta con ConceptoLibro)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='validador.conceptonovedades'),
        ),
        migrations.DeleteModel(
            name='ItemNovedades',
        ),
        migrations.DeleteModel(
            name='MapeoItemNovedades',
        ),
        migrations.AddIndex(
            model_name='conceptonovedades',
            index=models.Index(fields=['cliente', 'erp'], name='validador_c_cliente_ae46d9_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptonovedades',
            index=models.Index(fields=['cliente', 'erp', 'header_normalizado'], name='validador_c_cliente_9ade30_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptonovedades',
            index=models.Index(fields=['concepto_libro'], name='validador_c_concept_bb84d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptonovedades',
            unique_together={('cliente', 'erp', 'header_original')},
        ),
    ]
