# Generated by Django 5.2.10 on 2026-01-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0012_simplify_cierre_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptonovedades',
            name='sin_asignacion',
            field=models.BooleanField(default=False, help_text='True = este item no tiene equivalente en el libro y se ignorará en comparación'),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='estado',
            field=models.CharField(choices=[('carga_archivos', 'Carga de Archivos'), ('con_discrepancias', 'Con Discrepancias'), ('sin_discrepancias', 'Sin Discrepancias'), ('consolidado', 'Consolidado'), ('con_incidencias', 'Con Incidencias'), ('sin_incidencias', 'Sin Incidencias'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='carga_archivos', max_length=30),
        ),
    ]
