# Generated by Django 5.2.10 on 2026-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0013_add_sin_asignacion_to_concepto_novedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptolibro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('haberes_imponibles', 'Haberes Imponibles'), ('haberes_no_imponibles', 'Haberes No Imponibles'), ('descuentos_legales', 'Descuentos Legales'), ('otros_descuentos', 'Otros Descuentos'), ('aportes_patronales', 'Aportes Patronales'), ('info_adicional', 'Información Adicional')], help_text='Categoría asignada al concepto', max_length=30, null=True),
        ),
    ]
