# Generated by Django 5.2.10 on 2026-01-23 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_auditlog_model'),
        ('validador', '0014_remove_ignorar_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conceptonovedades',
            constraint=models.CheckConstraint(condition=models.Q(('concepto_libro__isnull', True), ('sin_asignacion', False), _connector='OR'), name='concepto_libro_xor_sin_asignacion'),
        ),
    ]
