# Generated by Django 5.2.10 on 2026-01-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0015_add_security_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomes',
            name='archivo_erp',
            field=models.ForeignKey(blank=True, help_text='Archivo ERP del cual se extrajo este movimiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='validador.archivoerp'),
        ),
        migrations.AddField(
            model_name='movimientomes',
            name='tipo_contrato',
            field=models.CharField(blank=True, help_text='Tipo de contrato: Plazo Fijo, Indefinido, etc.', max_length=50),
        ),
    ]
