# Generated by Django 5.2.10 on 2026-01-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0016_movimiento_tipo_contrato_archivo_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoanalista',
            name='archivo_analista',
            field=models.ForeignKey(blank=True, help_text='Archivo del analista del cual se extrajo este movimiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='validador.archivoanalista'),
        ),
        migrations.AddField(
            model_name='movimientoanalista',
            name='tipo_ausentismo',
            field=models.CharField(blank=True, help_text='Tipo de ausentismo original del archivo', max_length=100),
        ),
    ]
