# Generated by Django 5.2.10 on 2026-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0017_movimiento_analista_archivo_tipo_ausentismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancia',
            name='nombre_item_novedades',
            field=models.CharField(blank=True, help_text='Nombre del concepto en Novedades (cliente)', max_length=200),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='estado',
            field=models.CharField(choices=[('carga_archivos', 'Carga de Archivos'), ('archivos_listos', 'Archivos Listos'), ('comparando', 'Generando Discrepancias'), ('con_discrepancias', 'Con Discrepancias'), ('sin_discrepancias', 'Sin Discrepancias'), ('consolidado', 'Consolidado'), ('con_incidencias', 'Con Incidencias'), ('sin_incidencias', 'Sin Incidencias'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='carga_archivos', max_length=30),
        ),
        migrations.AlterField(
            model_name='discrepancia',
            name='nombre_item',
            field=models.CharField(blank=True, help_text='Nombre del concepto en el Libro (ERP)', max_length=200),
        ),
        migrations.AlterField(
            model_name='discrepancia',
            name='tipo',
            field=models.CharField(choices=[('monto_diferente', 'Monto Diferente'), ('falta_en_erp', 'Falta en ERP'), ('falta_en_cliente', 'Falta en Archivos Cliente')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='discrepancia',
            index=models.Index(fields=['cierre', 'origen'], name='validador_d_cierre__1418ce_idx'),
        ),
    ]
