# Generated by Django 5.2.10 on 2026-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validador', '0018_add_nombre_item_novedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoanalista',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('finiquito', 'Finiquito'), ('vacaciones', 'Vacaciones'), ('asistencia', 'Asistencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientomes',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('finiquito', 'Finiquito'), ('vacaciones', 'Vacaciones'), ('asistencia', 'Asistencia')], max_length=20),
        ),
    ]
